version: '3'
services:
  mongodb:
    image: 'mongo:latest'
    environment: 
      - MONGO_INITDB_DATABASE=cdr
    volumes:
      - ./scripts/a-mongo.js:/docker-entrypoint-initdb.d/a-mongo.js:ro
      - ./scripts/b-mongo.js:/docker-entrypoint-initdb.d/b-mongo.js:ro
    ports:
      - '27017-27019:27017-27019'

  csv-webapp:
    build: .
    depends_on: 
      - mongodb
    ports:
        - '5050:5050'
